name: restaurant
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutterfire_ui: ^0.4.3+20
  http: ^0.13.6
  intl: any
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
      - assets/maps.jpg
      - assets/american_pancake.jpg
      - assets/egg.jpg